stages:
  - build
  - test
  - deploy

# Build job
build:
  stage: build
  image: rust:latest
  script:
    - rustup update stable
    - rustup component add rustfmt clippy
    - cargo build --release

# Test job
test:
  stage: test
  image: rust:latest
  script:
    - rustup update stable
    - rustup component add rustfmt clippy
    - cargo test

# Deploy job for GitLab Pages
deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "🚀 Deploying /docs to public directory..."
    - mkdir -p public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public
  only:
    - main # Deploy only when pushing to the main branch
