version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:latest # Use the official Rust Docker image
    working_directory: ~/repo

jobs:
  build:
    executor: rust-executor
    steps:
      - checkout # Checkout the repository
      - run:
          name: Set up Rust
          command: |
            rustup update stable
            rustup component add rustfmt clippy
      - run:
          name: Install dependencies and build
          command: cargo build --release # Build the project
      - run:
          name: Run tests
          command: cargo test # Run tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: main # Trigger only for the 'main' branch
